# -*- coding: utf-8 -*-
"""Depth Anything V3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sPzAyad5DjjJPwfx2HVyHlnfadUWz1f
"""

# Commented out IPython magic to ensure Python compatibility.
# Cell 1: Install Depth Anything V3 & Dependencies
# !git clone https://github.com/ByteDance-Seed/Depth-Anything-3.git
# %cd Depth-Anything-3
# !pip install -q -r requirements.txt
# !pip install -q opencv-python matplotlib pillow torch torchvision

# Cell 1: Install required packages
# !pip install -q transformers torch torchvision pillow opencv-python matplotlib

# Cell 2: Run Depth Estimation pipeline
import os
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from transformers import pipeline

# Set device
device = 0 if torch.cuda.is_available() else -1

# Load Depth Anything model via Hugging Face Pipeline
pipe = pipeline(
    task="depth-estimation",
    model="depth-anything/Depth-Anything-V2-Base-hf",
    device=device
)

def estimate_pothole_depth(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    image_files = [f for f in os.listdir(input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    if not image_files:
        print(f"No images found in {input_folder}. Please upload cropped images to '{input_folder}' first.")
        return

    for filename in image_files:
        img_path = os.path.join(input_folder, filename)

        # Load cropped image
        raw_image = Image.open(img_path).convert("RGB")

        # Estimate depth
        result = pipe(raw_image)

        # Extract depth map array
        depth_pil = result["depth"]
        depth_map = np.array(depth_pil)

        # Colorize for visualization
        depth_norm = (depth_map - depth_map.min()) / (depth_map.max() - depth_map.min() + 1e-8)
        depth_colored = cv2.applyColorMap((depth_norm * 255).astype(np.uint8), cv2.COLORMAP_TURBO)
        depth_colored_rgb = cv2.cvtColor(depth_colored, cv2.COLOR_BGR2RGB)

        # Save side-by-side visualization
        fig, axes = plt.subplots(1, 2, figsize=(8, 4))
        axes[0].imshow(raw_image)
        axes[0].set_title("RF-DETR Crop")
        axes[0].axis("off")

        axes[1].imshow(depth_colored_rgb)
        axes[1].set_title("Depth Map")
        axes[1].axis("off")

        fig_save_path = os.path.join(output_folder, f"vis_{filename}")
        plt.tight_layout()
        plt.savefig(fig_save_path, bbox_inches='tight')
        plt.close()

        # Save raw numerical depth array
        npy_save_path = os.path.join(output_folder, f"raw_depth_{os.path.splitext(filename)[0]}.npy")
        np.save(npy_save_path, depth_map)

        print(f"Processed: {filename} -> Saved to {output_folder}")

# Set paths
INPUT_DIR = "/content/pothole_crops"
OUTPUT_DIR = "/content/pothole_depth_outputs"
os.makedirs(INPUT_DIR, exist_ok=True)

# Execute
estimate_pothole_depth(INPUT_DIR, OUTPUT_DIR)

# ==========================================
# Cell 2: Border-Anchored Pothole Pipeline
# ==========================================
import os
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from transformers import pipeline
from sklearn.linear_model import RANSACRegressor

# 1. Initialize Depth Estimation Pipeline
device = 0 if torch.cuda.is_available() else -1
pipe = pipeline(
    task="depth-estimation",
    model="depth-anything/Depth-Anything-V2-Base-hf",
    device=device
)

def detrend_border_plane(depth_map, border_width_ratio=0.10):
    """
    Fits a 2D baseline plane using ONLY border pixels (surrounding road surface)
    and subtracts it to isolate true cavity depth.
    """
    h, w = depth_map.shape
    border_w = max(2, int(w * border_width_ratio))
    border_h = max(2, int(h * border_width_ratio))

    # Generate mask for border pixels
    border_mask = np.zeros((h, w), dtype=bool)
    border_mask[:border_h, :] = True
    border_mask[-border_h:, :] = True
    border_mask[:, :border_w] = True
    border_mask[:, -border_w:] = True

    y_coords, x_coords = np.where(border_mask)
    z_values = depth_map[y_coords, x_coords]

    # Fit 2D plane via RANSAC
    X = np.column_stack((x_coords, y_coords))
    ransac = RANSACRegressor(residual_threshold=1.5, random_state=42)
    ransac.fit(X, z_values)

    # Predict ground plane across the entire crop matrix
    grid_y, grid_x = np.indices((h, w))
    full_grid = np.column_stack((grid_x.ravel(), grid_y.ravel()))
    baseline_plane = ransac.predict(full_grid).reshape(h, w)

    # Depth Anything V2 yields larger values closer to camera.
    # Road surface (baseline) is closer than the pothole pit (cavity).
    relative_cavity = baseline_plane - depth_map
    relative_cavity = np.maximum(0, relative_cavity)  # Retain cavity depths only

    return relative_cavity, baseline_plane

def analyze_pothole_crop(img_path, output_folder, upscale_factor=2):
    filename = os.path.basename(img_path)

    # Load and upscale image to sharpen micro-relief features
    raw_image = Image.open(img_path).convert("RGB")
    w, h = raw_image.size
    if upscale_factor > 1:
        raw_image = raw_image.resize((w * upscale_factor, h * upscale_factor), Image.LANCZOS)

    # Estimate raw depth
    result = pipe(raw_image)
    depth_map = np.array(result["depth"]).astype(np.float32)

    # Apply border-anchored detrending
    cavity_depth, baseline_plane = detrend_border_plane(depth_map)

    # Calculate Quantitative Metrics
    max_depth = np.max(cavity_depth)
    mean_depth = np.mean(cavity_depth[cavity_depth > 0]) if np.any(cavity_depth > 0) else 0.0
    lci_score = np.sum(cavity_depth)  # Localized Cavity Index (Volume Score)

    # Extract cross-section profiles through deepest point
    max_y, max_x = np.unravel_index(np.argmax(cavity_depth), cavity_depth.shape)
    x_slice = cavity_depth[max_y, :]
    y_slice = cavity_depth[:, max_x]

    # Generate Output Visualizations
    fig = plt.figure(figsize=(16, 4))

    # Subplot 1: Crop Image
    ax1 = fig.add_subplot(1, 4, 1)
    ax1.imshow(raw_image)
    ax1.set_title("RF-DETR Crop (Upscaled)")
    ax1.axis("off")

    # Subplot 2: Raw Depth Map
    ax2 = fig.add_subplot(1, 4, 2)
    ax2.imshow(depth_map, cmap="turbo")
    ax2.set_title("Raw Model Depth")
    ax2.axis("off")

    # Subplot 3: Detrended Cavity Depth Map
    ax3 = fig.add_subplot(1, 4, 3)
    im3 = ax3.imshow(cavity_depth, cmap="inferno")
    ax3.plot(max_x, max_y, 'cx', markersize=8, markeredgewidth=2)
    ax3.set_title(f"Detrended Cavity (LCI: {lci_score:.1f})")
    ax3.axis("off")
    plt.colorbar(im3, ax=ax3, fraction=0.046, pad=0.04)

    # Subplot 4: Axial Depth Profiles
    ax4 = fig.add_subplot(1, 4, 4)
    ax4.plot(x_slice, label='Horizontal (X)', color='red', linewidth=1.5)
    ax4.plot(y_slice, label='Vertical (Y)', color='cyan', linewidth=1.5)
    ax4.set_title("Depression Profile")
    ax4.set_xlabel("Pixels")
    ax4.set_ylabel("Relative Depth (ΔZ)")
    ax4.legend(fontsize=8)
    ax4.grid(True, linestyle='--', alpha=0.4)

    plt.tight_layout()
    save_path = os.path.join(output_folder, f"detrended_{filename}")
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()

    # Save raw array outputs
    np.save(os.path.join(output_folder, f"cavity_array_{os.path.splitext(filename)[0]}.npy"), cavity_depth)

    return {
        "filename": filename,
        "max_depth": max_depth,
        "mean_depth": mean_depth,
        "lci_score": lci_score
    }

# Execution Script
INPUT_DIR = "/content/pothole_crops"
OUTPUT_DIR = "/content/pothole_depth_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

image_files = [os.path.join(INPUT_DIR, f) for f in os.listdir(INPUT_DIR) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

if not image_files:
    print(f"No images found in '{INPUT_DIR}'. Please upload cropped images to this folder.")
else:
    for img_path in image_files:
        res = analyze_pothole_crop(img_path, OUTPUT_DIR)
        print(f"Processed: {res['filename']} | Max ΔZ: {res['max_depth']:.2f} | LCI Score: {res['lci_score']:.1f}")

# ==========================================
# Cell 2: Dashcam Video 3D Gaussian Depth Plotter
# ==========================================
import cv2
import torch
import numpy as np
import plotly.graph_objects as go
from scipy.ndimage import gaussian_filter
from PIL import Image
from transformers import pipeline

# Initialize Depth Estimation Model
device = 0 if torch.cuda.is_available() else -1
pipe = pipeline(
    task="depth-estimation",
    model="depth-anything/Depth-Anything-V2-Base-hf",
    device=device
)

def process_video_frame(video_path, frame_number=0):
    """Extracts a specific frame from the dashcam video."""
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
    ret, frame = cap.read()
    cap.release()
    if not ret:
        raise ValueError(f"Could not read frame {frame_number} from video {video_path}")
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    return Image.fromarray(frame_rgb)

def generate_3d_gaussian_road_plot(image_pil, downsample_factor=4, gaussian_sigma=2.0):
    """
    Estimates depth, projects to 3D, fits a Gaussian spatial filter,
    and plots an interactive 3D surface mesh using Plotly.
    """
    # 1. Run Depth Anything Model
    raw_w, raw_h = image_pil.size
    result = pipe(image_pil)
    depth_map = np.array(result["depth"]).astype(np.float32)

    # 2. Downsample matrix for fast 3D rendering
    depth_sub = depth_map[::downsample_factor, ::downsample_factor]
    img_sub = np.array(image_pil)[::downsample_factor, ::downsample_factor]
    h, w = depth_sub.shape

    # 3. Apply 3D Gaussian smoothing to reduce sensor/monocular noise
    depth_smoothed = gaussian_filter(depth_sub, sigma=gaussian_sigma)

    # 4. Construct 3D Coordinate Grid (X, Y, Z)
    # Estimate simple intrinsic parameters based on frame dimensions
    fx = fy = max(w, h)
    cx, cy = w / 2.0, h / 2.0

    u = np.arange(w)
    v = np.arange(h)
    u_grid, v_grid = np.meshgrid(u, v)

    # Re-project to 3D Cartesian coordinates
    Z = depth_smoothed
    X = (u_grid - cx) * Z / fx
    Y = -(v_grid - cy) * Z / fy  # Invert Y for correct visual orientation

    # Convert RGB frame into hex colors for 3D point cloud mapping
    colors = [
        f'rgb({img_sub[r, c, 0]},{img_sub[r, c, 1]},{img_sub[r, c, 2]})'
        for r in range(h) for c in range(w)
    ]

    # 5. Render Interactive 3D Surface Plot
    fig = go.Figure(data=[
        go.Surface(
            x=X,
            y=Y,
            z=Z,
            surfacecolor=depth_smoothed,
            colorscale='Turbo',
            colorbar=dict(title='Depth (Z)')
        )
    ])

    fig.update_layout(
        title="Dashcam 3D Gaussian Surface Depth Reconstruction",
        scene=dict(
            xaxis_title="Camera X (m)",
            yaxis_title="Road Distance Y (m)",
            zaxis_title="Elevation Z (m)",
            aspectratio=dict(x=1, y=2, z=0.5),
            camera=dict(eye=dict(x=0, y=-1.5, z=0.8))
        ),
        margin=dict(l=0, r=0, b=0, t=40)
    )

    return fig

# ==========================================
# Execution Example
# ==========================================
# Replace with your local dashcam video file path
VIDEO_FILE = "/content/0001.mp4"

# Extract frame 30 and generate plot (Run inside Colab to view interactive figure)
try:
    frame_image = process_video_frame(VIDEO_FILE, frame_number=30)
    fig_3d = generate_3d_gaussian_road_plot(frame_image, downsample_factor=4, gaussian_sigma=1.5)
    fig_3d.show()
except Exception as e:
    print(f"Error executing pipeline: {e}")

import numpy as np

def save_pothole_ply(X, Y, Z, output_path="/content/pothole_3d.ply"):
    """Converts (X, Y, Z) coordinates into a PLY Point Cloud file without Open3D."""
    # Flatten and stack coordinates
    points = np.column_stack((X.ravel(), Y.ravel(), Z.ravel()))

    # Filter out NaNs or invalid values
    valid_mask = ~np.isnan(points).any(axis=1)
    points = points[valid_mask]

    # Manually write PLY header and data
    num_points = len(points)
    header = [
        "ply",
        "format ascii 1.0",
        f"element vertex {num_points}",
        "property float x",
        "property float y",
        "property float z",
        "end_header"
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(header) + "\n")
        np.savetxt(f, points, fmt="%.6f %.6f %.6f")

    print(f"Successfully saved {num_points} points to: {output_path}")

# To download to your PC:
from google.colab import files
# files.download("/content/pothole_3d.ply")

# ==========================================
# Cell 2: Generate and Save 3D Gaussian & PLY Files
# ==========================================
import os
import cv2
import torch
import numpy as np
from PIL import Image
from transformers import pipeline
from google.colab import files

def generate_3d_splat_from_video(video_path="/content/000.mp4", frame_idx=0, downsample=2):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found at '{video_path}'. Please check your file name and location.")

    print(f"Loading Depth Model & Processing '{video_path}'...")
    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Base-hf", device=device)

    # 1. Extract Video Frame
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Could not read frame {frame_idx} from video.")

    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    raw_pil = Image.fromarray(frame_rgb)

    # 2. Run Monocular Depth Estimation
    result = pipe(raw_pil)
    depth_map = np.array(result["depth"]).astype(np.float32)

    # 3. Downsample for cleaner 3D point density
    depth_sub = depth_map[::downsample, ::downsample]
    rgb_sub = frame_rgb[::downsample, ::downsample]
    h, w = depth_sub.shape

    # 4. Convert 2D Depth to 3D Cartesian Coordinates (X, Y, Z)
    fx = fy = max(w, h)
    cx, cy = w / 2.0, h / 2.0

    u, v = np.meshgrid(np.arange(w), np.arange(h))
    Z = depth_sub
    X = (u - cx) * Z / fx
    Y = -(v - cy) * Z / fy  # Invert Y for correct camera orientation

    # Flatten arrays
    x_pts = X.ravel()
    y_pts = Y.ravel()
    z_pts = Z.ravel()
    r_pts = rgb_sub[:, :, 0].ravel()
    g_pts = rgb_sub[:, :, 1].ravel()
    b_pts = rgb_sub[:, :, 2].ravel()

    valid_mask = ~np.isnan(z_pts)
    x_pts, y_pts, z_pts = x_pts[valid_mask], y_pts[valid_mask], z_pts[valid_mask]
    r_pts, g_pts, b_pts = r_pts[valid_mask], g_pts[valid_mask], b_pts[valid_mask]
    num_pts = len(x_pts)

    # ----------------------------------------------------
    # Export 1: Standard RGB Point Cloud PLY
    # ----------------------------------------------------
    std_ply_path = "/content/000_pointcloud.ply"
    std_header = f"""ply
format ascii 1.0
element vertex {num_pts}
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
"""
    std_data = np.column_stack((x_pts, y_pts, z_pts, r_pts, g_pts, b_pts))
    with open(std_ply_path, "w") as f:
        f.write(std_header)
        np.savetxt(f, std_data, fmt="%.4f %.4f %.4f %d %d %d")
    print(f"Saved: {std_ply_path}")

    # ----------------------------------------------------
    # Export 2: True 3D Gaussian Splat PLY
    # ----------------------------------------------------
    # Convert RGB [0-255] to Spherical Harmonics Zero-Order (f_dc)
    SH_C0 = 0.28209479177387814
    f_dc_0 = ((r_pts / 255.0) - 0.5) / SH_C0
    f_dc_1 = ((g_pts / 255.0) - 0.5) / SH_C0
    f_dc_2 = ((b_pts / 255.0) - 0.5) / SH_C0

    # Define Gaussian parameters (Log scale for size, Logit for opacity)
    scale = np.full(num_pts, -5.5, dtype=np.float32)  # Log scale radius
    opacity = np.full(num_pts, 3.0, dtype=np.float32) # High opacity logit
    rot_0 = np.ones(num_pts, dtype=np.float32)        # Quaternion W
    rot_123 = np.zeros(num_pts, dtype=np.float32)     # Quaternion X, Y, Z
    normals = np.zeros(num_pts, dtype=np.float32)     # Normals

    gs_ply_path = "/content/000_gaussian_splat.ply"
    gs_header = f"""ply
format ascii 1.0
element vertex {num_pts}
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
"""
    gs_data = np.column_stack((
        x_pts, y_pts, z_pts,
        normals, normals, normals,
        f_dc_0, f_dc_1, f_dc_2,
        opacity,
        scale, scale, scale,
        rot_0, rot_123, rot_123, rot_123
    ))

    with open(gs_ply_path, "w") as f:
        f.write(gs_header)
        np.savetxt(f, gs_data, fmt="%.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f %.4f")
    print(f"Saved: {gs_ply_path}")

    # Trigger download of Gaussian Splat PLY to local computer
    files.download(gs_ply_path)

# Execute
generate_3d_splat_from_video("/content/0001.mp4", frame_idx=0, downsample=2)

# ==========================================
# Cell 2: Corrected 3D Depth Viewer
# ==========================================
import os
import cv2
import torch
import json
import numpy as np
from PIL import Image
from transformers import pipeline
from IPython.display import HTML, display

def render_fixed_3d_road(video_path="/content/0001.mp4", frame_idx=0, downsample=2):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found at '{video_path}'. Please upload it to /content/")

    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Base-hf", device=device)

    # 1. Extract Video Frame
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Could not read frame {frame_idx} from video.")

    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    raw_pil = Image.fromarray(frame_rgb)

    # 2. Run Monocular Depth Estimation
    result = pipe(raw_pil)
    disparity_map = np.array(result["depth"]).astype(np.float32)

    # 3. Downsample for render performance
    disp_sub = disparity_map[::downsample, ::downsample]
    rgb_sub = frame_rgb[::downsample, ::downsample]
    h, w = disp_sub.shape

    # 4. Correct Disparity to Physical Distance Z
    # Normalize disparity map to [0, 1]
    disp_norm = (disp_sub - disp_sub.min()) / (disp_sub.max() - disp_sub.min() + 1e-8)

    # Invert disparity to obtain metric-proportional depth (Distance Z)
    # Near objects (disp=1) -> Z=1m | Far objects (disp=0) -> Z=15m
    Z = 1.0 / (disp_norm * 0.9 + 0.07)

    # 5. Ray Back-Projection to 3D Space
    fx = fy = max(w, h) * 0.8
    cx, cy = w / 2.0, h / 2.0

    u, v = np.meshgrid(np.arange(w), np.arange(h))
    X = (u - cx) * Z / fx
    Y = -(v - cy) * Z / fy  # Invert Y axis for correct height orientation

    # 6. Flatten and Filter Valid Points
    x_pts = X.ravel()
    y_pts = Y.ravel()
    z_pts = Z.ravel()
    r_pts = (rgb_sub[:, :, 0].ravel() / 255.0).astype(np.float32)
    g_pts = (rgb_sub[:, :, 1].ravel() / 255.0).astype(np.float32)
    b_pts = (rgb_sub[:, :, 2].ravel() / 255.0).astype(np.float32)

    valid_mask = ~np.isnan(z_pts)
    positions = np.column_stack((x_pts[valid_mask], y_pts[valid_mask], z_pts[valid_mask])).ravel().tolist()
    colors = np.column_stack((r_pts[valid_mask], g_pts[valid_mask], b_pts[valid_mask])).ravel().tolist()

    # 7. Render Fixed Three.js HTML/JS WebGL Canvas
    html_code = f"""
    <div id="splat-container" style="width: 100%; height: 600px; background-color: #0d0d11; border-radius: 8px;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
    <script>
        (function() {{
            const container = document.getElementById('splat-container');
            const scene = new THREE.Scene();
            scene.background = new THREE.Color(0x0d0d11);

            const camera = new THREE.PerspectiveCamera(55, container.clientWidth / container.clientHeight, 0.1, 100);

            const renderer = new THREE.WebGLRenderer({{ antialias: true }});
            renderer.setSize(container.clientWidth, container.clientHeight);
            renderer.setPixelRatio(window.devicePixelRatio);
            container.appendChild(renderer.domElement);

            const controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.05;

            const positions = new Float32Array({json.dumps(positions)});
            const colors = new Float32Array({json.dumps(colors)});

            const geometry = new THREE.BufferGeometry();
            geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
            geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

            const material = new THREE.PointsMaterial({{
                size: 0.05,
                vertexColors: true,
                sizeAttenuation: true
            }});

            const pointCloud = new THREE.Points(geometry, material);
            scene.add(pointCloud);

            // Set camera target to middle of road point cloud
            geometry.computeBoundingBox();
            const center = new THREE.Vector3();
            geometry.boundingBox.getCenter(center);

            controls.target.copy(center);
            camera.position.set(center.x, center.y + 2, center.z - 4);
            controls.update();

            function animate() {{
                requestAnimationFrame(animate);
                controls.update();
                renderer.render(scene, camera);
            }}
            animate();
        }})();
    </script>
    """
    display(HTML(html_code))

# Execute fixed 3D viewer
render_fixed_3d_road("/content/0001.mp4", frame_idx=0, downsample=2)

# ==========================================
# Cell 2: Segmented Pothole 3D Splat Viewer
# ==========================================
import os
import cv2
import torch
import json
import numpy as np
from PIL import Image
from transformers import pipeline
from sklearn.linear_model import RANSACRegressor
from IPython.display import HTML, display

def render_segmented_pothole_3d(
    video_path="/content/0001.mp4",
    frame_idx=0,
    downsample=2,
    depth_threshold=0.08
):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found at '{video_path}'. Please upload it to /content/")

    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Base-hf", device=device)

    # 1. Extract Video Frame
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Could not read frame {frame_idx} from video.")

    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    raw_pil = Image.fromarray(frame_rgb)

    # 2. Run Monocular Depth Estimation
    result = pipe(raw_pil)
    disparity_map = np.array(result["depth"]).astype(np.float32)

    # 3. Downsample for Performance
    disp_sub = disparity_map[::downsample, ::downsample]
    rgb_sub = frame_rgb[::downsample, ::downsample]
    h, w = disp_sub.shape

    # 4. Convert Disparity to Physical Distance Z
    disp_norm = (disp_sub - disp_sub.min()) / (disp_sub.max() - disp_sub.min() + 1e-8)
    Z = 1.0 / (disp_norm * 0.9 + 0.07)

    # 5. Project 2D Depth to 3D Cartesian Coordinates (X, Y, Z)
    fx = fy = max(w, h) * 0.8
    cx, cy = w / 2.0, h / 2.0

    u, v = np.meshgrid(np.arange(w), np.arange(h))
    X = (u - cx) * Z / fx
    Y = -(v - cy) * Z / fy  # Invert Y for upright orientation

    # Flatten coordinates & colors
    x_pts = X.ravel()
    y_pts = Y.ravel()
    z_pts = Z.ravel()
    r_pts = (rgb_sub[:, :, 0].ravel() / 255.0).astype(np.float32)
    g_pts = (rgb_sub[:, :, 1].ravel() / 255.0).astype(np.float32)
    b_pts = (rgb_sub[:, :, 2].ravel() / 255.0).astype(np.float32)

    valid_mask = ~np.isnan(z_pts)
    x_valid, y_valid, z_valid = x_pts[valid_mask], y_pts[valid_mask], z_pts[valid_mask]
    r_valid, g_valid, b_valid = r_pts[valid_mask], g_pts[valid_mask], b_pts[valid_mask]

    # 6. Fit Ground Plane via RANSAC to Isolate Potholes
    # Sample points from lower 60% of image (road area) to avoid sky/horizon fitting
    road_mask = (y_valid < np.median(y_valid))
    X_road = np.column_stack((x_valid[road_mask], y_valid[road_mask]))
    Z_road = z_valid[road_mask]

    ransac = RANSACRegressor(residual_threshold=0.1, random_state=42)
    ransac.fit(X_road, Z_road)

    # Calculate distance from fitted plane for all points
    X_all = np.column_stack((x_valid, y_valid))
    ideal_Z = ransac.predict(X_all)
    delta_Z = z_valid - ideal_Z  # Positive means point dips below fitted road surface

    # 7. Apply Thermal Cavity Highlight Mask
    pothole_mask = (delta_Z > depth_threshold) & (y_valid < np.median(y_valid))

    # Color mapping: Normal RGB for road, Neon Red/Yellow Gradient for Pothole
    r_out, g_out, b_out = r_valid.copy(), g_valid.copy(), b_valid.copy()

    if np.any(pothole_mask):
        max_dep = np.max(delta_Z[pothole_mask])
        norm_dep = (delta_Z[pothole_mask] - depth_threshold) / (max_dep - depth_threshold + 1e-6)

        # Highlight: Yellow (1.0, 0.9, 0.0) -> Red (1.0, 0.0, 0.0)
        r_out[pothole_mask] = 1.0
        g_out[pothole_mask] = 0.9 * (1.0 - norm_dep)
        b_out[pothole_mask] = 0.0

    positions = np.column_stack((x_valid, y_valid, z_valid)).ravel().tolist()
    colors = np.column_stack((r_out, g_out, b_out)).ravel().tolist()

    # 8. Render Interactive Three.js Viewport
    html_code = f"""
    <div id="splat-container" style="width: 100%; height: 600px; background-color: #0d0d11; border-radius: 8px;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
    <script>
        (function() {{
            const container = document.getElementById('splat-container');
            const scene = new THREE.Scene();
            scene.background = new THREE.Color(0x0d0d11);

            const camera = new THREE.PerspectiveCamera(55, container.clientWidth / container.clientHeight, 0.1, 100);

            const renderer = new THREE.WebGLRenderer({{ antialias: true }});
            renderer.setSize(container.clientWidth, container.clientHeight);
            renderer.setPixelRatio(window.devicePixelRatio);
            container.appendChild(renderer.domElement);

            const controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.05;

            const positions = new Float32Array({json.dumps(positions)});
            const colors = new Float32Array({json.dumps(colors)});

            const geometry = new THREE.BufferGeometry();
            geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
            geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

            const material = new THREE.PointsMaterial({{
                size: 0.06,
                vertexColors: true,
                sizeAttenuation: true
            }});

            const pointCloud = new THREE.Points(geometry, material);
            scene.add(pointCloud);

            // Recenter focus on the road plane
            geometry.computeBoundingBox();
            const center = new THREE.Vector3();
            geometry.boundingBox.getCenter(center);

            controls.target.copy(center);
            camera.position.set(center.x, center.y + 2.5, center.z - 4.5);
            controls.update();

            function animate() {{
                requestAnimationFrame(animate);
                controls.update();
                renderer.render(scene, camera);
            }}
            animate();
        }})();
    </script>
    """
    display(HTML(html_code))

# Execute Viewer with Highlighted Potholes
render_segmented_pothole_3d("/content/0002.mp4", frame_idx=0, downsample=2, depth_threshold=0.08)

# ==========================================
# Cell 2: Segmented Pothole 3D Splat Viewer
# ==========================================
import os
import cv2
import torch
import json
import numpy as np
from PIL import Image
from transformers import pipeline
from sklearn.linear_model import RANSACRegressor
from IPython.display import HTML, display

def render_segmented_pothole_3d(
    video_path="/content/0004.mp4",
    frame_idx=0,
    downsample=2,
    depth_threshold=0.08
):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found at '{video_path}'. Please upload it to /content/")

    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Base-hf", device=device)

    # 1. Extract Video Frame
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Could not read frame {frame_idx} from video.")

    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    raw_pil = Image.fromarray(frame_rgb)

    # 2. Run Monocular Depth Estimation
    result = pipe(raw_pil)
    disparity_map = np.array(result["depth"]).astype(np.float32)

    # 3. Downsample for Performance
    disp_sub = disparity_map[::downsample, ::downsample]
    rgb_sub = frame_rgb[::downsample, ::downsample]
    h, w = disp_sub.shape

    # 4. Convert Disparity to Physical Distance Z
    disp_norm = (disp_sub - disp_sub.min()) / (disp_sub.max() - disp_sub.min() + 1e-8)
    Z = 1.0 / (disp_norm * 0.9 + 0.07)

    # 5. Project 2D Depth to 3D Cartesian Coordinates (X, Y, Z)
    fx = fy = max(w, h) * 0.8
    cx, cy = w / 2.0, h / 2.0

    u, v = np.meshgrid(np.arange(w), np.arange(h))
    X = (u - cx) * Z / fx
    Y = -(v - cy) * Z / fy  # Invert Y for upright orientation

    # Flatten coordinates & colors
    x_pts = X.ravel()
    y_pts = Y.ravel()
    z_pts = Z.ravel()
    r_pts = (rgb_sub[:, :, 0].ravel() / 255.0).astype(np.float32)
    g_pts = (rgb_sub[:, :, 1].ravel() / 255.0).astype(np.float32)
    b_pts = (rgb_sub[:, :, 2].ravel() / 255.0).astype(np.float32)

    valid_mask = ~np.isnan(z_pts)
    x_valid, y_valid, z_valid = x_pts[valid_mask], y_pts[valid_mask], z_pts[valid_mask]
    r_valid, g_valid, b_valid = r_pts[valid_mask], g_pts[valid_mask], b_pts[valid_mask]

    # 6. Fit Ground Plane via RANSAC to Isolate Potholes
    # Sample points from lower 60% of image (road area) to avoid sky/horizon fitting
    road_mask = (y_valid < np.median(y_valid))
    X_road = np.column_stack((x_valid[road_mask], y_valid[road_mask]))
    Z_road = z_valid[road_mask]

    ransac = RANSACRegressor(residual_threshold=0.1, random_state=42)
    ransac.fit(X_road, Z_road)

    # Calculate distance from fitted plane for all points
    X_all = np.column_stack((x_valid, y_valid))
    ideal_Z = ransac.predict(X_all)
    delta_Z = z_valid - ideal_Z  # Positive means point dips below fitted road surface

    # 7. Apply Thermal Cavity Highlight Mask
    pothole_mask = (delta_Z > depth_threshold) & (y_valid < np.median(y_valid))

    # Color mapping: Normal RGB for road, Neon Red/Yellow Gradient for Pothole
    r_out, g_out, b_out = r_valid.copy(), g_valid.copy(), b_valid.copy()

    if np.any(pothole_mask):
        max_dep = np.max(delta_Z[pothole_mask])
        norm_dep = (delta_Z[pothole_mask] - depth_threshold) / (max_dep - depth_threshold + 1e-6)

        # Highlight: Yellow (1.0, 0.9, 0.0) -> Red (1.0, 0.0, 0.0)
        r_out[pothole_mask] = 1.0
        g_out[pothole_mask] = 0.9 * (1.0 - norm_dep)
        b_out[pothole_mask] = 0.0

    positions = np.column_stack((x_valid, y_valid, z_valid)).ravel().tolist()
    colors = np.column_stack((r_out, g_out, b_out)).ravel().tolist()

    # 8. Render Interactive Three.js Viewport
    html_code = f"""
    <div id="splat-container" style="width: 100%; height: 600px; background-color: #0d0d11; border-radius: 8px;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
    <script>
        (function() {{
            const container = document.getElementById('splat-container');
            const scene = new THREE.Scene();
            scene.background = new THREE.Color(0x0d0d11);

            const camera = new THREE.PerspectiveCamera(55, container.clientWidth / container.clientHeight, 0.1, 100);

            const renderer = new THREE.WebGLRenderer({{ antialias: true }});
            renderer.setSize(container.clientWidth, container.clientHeight);
            renderer.setPixelRatio(window.devicePixelRatio);
            container.appendChild(renderer.domElement);

            const controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.05;

            const positions = new Float32Array({json.dumps(positions)});
            const colors = new Float32Array({json.dumps(colors)});

            const geometry = new THREE.BufferGeometry();
            geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
            geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

            const material = new THREE.PointsMaterial({{
                size: 0.06,
                vertexColors: true,
                sizeAttenuation: true
            }});

            const pointCloud = new THREE.Points(geometry, material);
            scene.add(pointCloud);

            // Recenter focus on the road plane
            geometry.computeBoundingBox();
            const center = new THREE.Vector3();
            geometry.boundingBox.getCenter(center);

            controls.target.copy(center);
            camera.position.set(center.x, center.y + 2.5, center.z - 4.5);
            controls.update();

            function animate() {{
                requestAnimationFrame(animate);
                controls.update();
                renderer.render(scene, camera);
            }}
            animate();
        }})();
    </script>
    """
    display(HTML(html_code))

# Execute Viewer with Highlighted Potholes
render_segmented_pothole_3d("/content/0004.mp4", frame_idx=0, downsample=2, depth_threshold=0.08)

"""## Perimeter-Restricted Baseline Plane:"""

# ==========================================
# Cell 2: Adaptive 3D Segmented Pothole Viewer
# ==========================================
import os
import cv2
import torch
import json
import numpy as np
from PIL import Image
from transformers import pipeline
from sklearn.linear_model import RANSACRegressor
from IPython.display import HTML, display

def render_adaptive_pothole_3d(
    video_path="/content/0004.mp4",
    frame_idx=0,
    downsample=2,
    sensitivity="medium"  # Options: "high", "medium", "low"
):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found at '{video_path}'. Please upload it to /content/")

    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Base-hf", device=device)

    # 1. Extract Video Frame
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Could not read frame {frame_idx} from video.")

    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    raw_pil = Image.fromarray(frame_rgb)

    # 2. Run Monocular Depth Estimation
    result = pipe(raw_pil)
    disparity_map = np.array(result["depth"]).astype(np.float32)

    # 3. Downsample matrix for rendering speed
    disp_sub = disparity_map[::downsample, ::downsample]
    rgb_sub = frame_rgb[::downsample, ::downsample]
    h, w = disp_sub.shape

    # 4. Convert Disparity map to Distance Z
    disp_norm = (disp_sub - disp_sub.min()) / (disp_sub.max() - disp_sub.min() + 1e-8)
    Z = 1.0 / (disp_norm * 0.9 + 0.07)

    # 5. Ray Back-Projection to 3D Cartesian Coordinates
    fx = fy = max(w, h) * 0.8
    cx, cy = w / 2.0, h / 2.0

    u, v = np.meshgrid(np.arange(w), np.arange(h))
    X = (u - cx) * Z / fx
    Y = -(v - cy) * Z / fy

    x_pts, y_pts, z_pts = X.ravel(), Y.ravel(), Z.ravel()
    r_pts = (rgb_sub[:, :, 0].ravel() / 255.0).astype(np.float32)
    g_pts = (rgb_sub[:, :, 1].ravel() / 255.0).astype(np.float32)
    b_pts = (rgb_sub[:, :, 2].ravel() / 255.0).astype(np.float32)

    valid_mask = ~np.isnan(z_pts)
    x_valid, y_valid, z_valid = x_pts[valid_mask], y_pts[valid_mask], z_pts[valid_mask]
    r_valid, g_valid, b_valid = r_pts[valid_mask], g_pts[valid_mask], b_pts[valid_mask]

    # 6. Fit Baseline Surface using Perimeter Points ONLY
    grid_u, grid_v = u.ravel()[valid_mask], v.ravel()[valid_mask]
    border_margin = 0.12 # Use outer 12% frame border as baseline ground reference
    border_mask = (
        (grid_u < w * border_margin) | (grid_u > w * (1 - border_margin)) |
        (grid_v < h * border_margin) | (grid_v > h * (1 - border_margin))
    )

    X_border = np.column_stack((x_valid[border_mask], y_valid[border_mask]))
    Z_border = z_valid[border_mask]

    ransac = RANSACRegressor(residual_threshold=0.1, random_state=42)
    ransac.fit(X_border, Z_border)

    # Predict baseline road depth across the entire mesh
    X_all = np.column_stack((x_valid, y_valid))
    ideal_Z = ransac.predict(X_all)
    delta_Z = z_valid - ideal_Z  # Positive values indicate depression below road plane

    # 7. Dynamic Adaptive Threshold Calculation
    positive_dips = delta_Z[delta_Z > 0]
    if len(positive_dips) > 0:
        std_dev = np.std(positive_dips)
        median_dip = np.median(positive_dips)

        # Adjust threshold based on selected sensitivity mode
        sens_factors = {"high": 0.8, "medium": 1.5, "low": 2.5}
        factor = sens_factors.get(sensitivity, 1.5)

        dynamic_threshold = median_dip + (factor * std_dev)
        dynamic_threshold = max(0.015, dynamic_threshold)  # Noise floor cap
    else:
        dynamic_threshold = 0.05

    # Mask for highlighted cavity regions
    pothole_mask = delta_Z > dynamic_threshold

    # 8. Apply Color Map Highlight
    r_out, g_out, b_out = r_valid.copy(), g_valid.copy(), b_valid.copy()

    if np.any(pothole_mask):
        max_dep = np.percentile(delta_Z[pothole_mask], 98) # Avoid extreme pixel noise
        norm_dep = (delta_Z[pothole_mask] - dynamic_threshold) / (max_dep - dynamic_threshold + 1e-6)
        norm_dep = np.clip(norm_dep, 0.0, 1.0)

        # Highlight: Yellow (1.0, 0.9, 0.0) -> Crimson Red (1.0, 0.0, 0.0)
        r_out[pothole_mask] = 1.0
        g_out[pothole_mask] = 0.9 * (1.0 - norm_dep)
        b_out[pothole_mask] = 0.0

    positions = np.column_stack((x_valid, y_valid, z_valid)).ravel().tolist()
    colors = np.column_stack((r_out, g_out, b_out)).ravel().tolist()

    print(f"Adaptive Detection Threshold set to: {dynamic_threshold:.4f} ΔZ")

    # 9. Render Interactive Three.js Viewport
    html_code = f"""
    <div id="splat-container" style="width: 100%; height: 600px; background-color: #0d0d11; border-radius: 8px;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
    <script>
        (function() {{
            const container = document.getElementById('splat-container');
            const scene = new THREE.Scene();
            scene.background = new THREE.Color(0x0d0d11);

            const camera = new THREE.PerspectiveCamera(55, container.clientWidth / container.clientHeight, 0.1, 100);

            const renderer = new THREE.WebGLRenderer({{ antialias: true }});
            renderer.setSize(container.clientWidth, container.clientHeight);
            renderer.setPixelRatio(window.devicePixelRatio);
            container.appendChild(renderer.domElement);

            const controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.05;

            const positions = new Float32Array({json.dumps(positions)});
            const colors = new Float32Array({json.dumps(colors)});

            const geometry = new THREE.BufferGeometry();
            geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
            geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

            const material = new THREE.PointsMaterial({{
                size: 0.06,
                vertexColors: true,
                sizeAttenuation: true
            }});

            const pointCloud = new THREE.Points(geometry, material);
            scene.add(pointCloud);

            geometry.computeBoundingBox();
            const center = new THREE.Vector3();
            geometry.boundingBox.getCenter(center);

            controls.target.copy(center);
            camera.position.set(center.x, center.y + 2.5, center.z - 4.5);
            controls.update();

            function animate() {{
                requestAnimationFrame(animate);
                controls.update();
                renderer.render(scene, camera);
            }}
            animate();
        }})();
    </script>
    """
    display(HTML(html_code))

# Execute Viewer (Try sensitivity="high" if the pothole is extremely shallow)
render_adaptive_pothole_3d("/content/0004.mp4", frame_idx=0, downsample=2, sensitivity="high")

# ==========================================
# Cell 2: Adaptive 3D Segmented Pothole Viewer
# ==========================================
import os
import cv2
import torch
import json
import numpy as np
from PIL import Image
from transformers import pipeline
from sklearn.linear_model import RANSACRegressor
from IPython.display import HTML, display

def render_adaptive_pothole_3d(
    video_path="/content/0005.mp4",
    frame_idx=0,
    downsample=2,
    sensitivity="medium"  # Options: "high", "medium", "low"
):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found at '{video_path}'. Please upload it to /content/")

    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Base-hf", device=device)

    # 1. Extract Video Frame
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Could not read frame {frame_idx} from video.")

    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    raw_pil = Image.fromarray(frame_rgb)

    # 2. Run Monocular Depth Estimation
    result = pipe(raw_pil)
    disparity_map = np.array(result["depth"]).astype(np.float32)

    # 3. Downsample matrix for rendering speed
    disp_sub = disparity_map[::downsample, ::downsample]
    rgb_sub = frame_rgb[::downsample, ::downsample]
    h, w = disp_sub.shape

    # 4. Convert Disparity map to Distance Z
    disp_norm = (disp_sub - disp_sub.min()) / (disp_sub.max() - disp_sub.min() + 1e-8)
    Z = 1.0 / (disp_norm * 0.9 + 0.07)

    # 5. Ray Back-Projection to 3D Cartesian Coordinates
    fx = fy = max(w, h) * 0.8
    cx, cy = w / 2.0, h / 2.0

    u, v = np.meshgrid(np.arange(w), np.arange(h))
    X = (u - cx) * Z / fx
    Y = -(v - cy) * Z / fy

    x_pts, y_pts, z_pts = X.ravel(), Y.ravel(), Z.ravel()
    r_pts = (rgb_sub[:, :, 0].ravel() / 255.0).astype(np.float32)
    g_pts = (rgb_sub[:, :, 1].ravel() / 255.0).astype(np.float32)
    b_pts = (rgb_sub[:, :, 2].ravel() / 255.0).astype(np.float32)

    valid_mask = ~np.isnan(z_pts)
    x_valid, y_valid, z_valid = x_pts[valid_mask], y_pts[valid_mask], z_pts[valid_mask]
    r_valid, g_valid, b_valid = r_pts[valid_mask], g_pts[valid_mask], b_pts[valid_mask]

    # 6. Fit Baseline Surface using Perimeter Points ONLY
    grid_u, grid_v = u.ravel()[valid_mask], v.ravel()[valid_mask]
    border_margin = 0.12 # Use outer 12% frame border as baseline ground reference
    border_mask = (
        (grid_u < w * border_margin) | (grid_u > w * (1 - border_margin)) |
        (grid_v < h * border_margin) | (grid_v > h * (1 - border_margin))
    )

    X_border = np.column_stack((x_valid[border_mask], y_valid[border_mask]))
    Z_border = z_valid[border_mask]

    ransac = RANSACRegressor(residual_threshold=0.1, random_state=42)
    ransac.fit(X_border, Z_border)

    # Predict baseline road depth across the entire mesh
    X_all = np.column_stack((x_valid, y_valid))
    ideal_Z = ransac.predict(X_all)
    delta_Z = z_valid - ideal_Z  # Positive values indicate depression below road plane

    # 7. Dynamic Adaptive Threshold Calculation
    positive_dips = delta_Z[delta_Z > 0]
    if len(positive_dips) > 0:
        std_dev = np.std(positive_dips)
        median_dip = np.median(positive_dips)

        # Adjust threshold based on selected sensitivity mode
        sens_factors = {"high": 0.8, "medium": 1.5, "low": 2.5}
        factor = sens_factors.get(sensitivity, 1.5)

        dynamic_threshold = median_dip + (factor * std_dev)
        dynamic_threshold = max(0.015, dynamic_threshold)  # Noise floor cap
    else:
        dynamic_threshold = 0.05

    # Mask for highlighted cavity regions
    pothole_mask = delta_Z > dynamic_threshold

    # 8. Apply Color Map Highlight
    r_out, g_out, b_out = r_valid.copy(), g_valid.copy(), b_valid.copy()

    if np.any(pothole_mask):
        max_dep = np.percentile(delta_Z[pothole_mask], 98) # Avoid extreme pixel noise
        norm_dep = (delta_Z[pothole_mask] - dynamic_threshold) / (max_dep - dynamic_threshold + 1e-6)
        norm_dep = np.clip(norm_dep, 0.0, 1.0)

        # Highlight: Yellow (1.0, 0.9, 0.0) -> Crimson Red (1.0, 0.0, 0.0)
        r_out[pothole_mask] = 1.0
        g_out[pothole_mask] = 0.9 * (1.0 - norm_dep)
        b_out[pothole_mask] = 0.0

    positions = np.column_stack((x_valid, y_valid, z_valid)).ravel().tolist()
    colors = np.column_stack((r_out, g_out, b_out)).ravel().tolist()

    print(f"Adaptive Detection Threshold set to: {dynamic_threshold:.4f} ΔZ")

    # 9. Render Interactive Three.js Viewport
    html_code = f"""
    <div id="splat-container" style="width: 100%; height: 600px; background-color: #0d0d11; border-radius: 8px;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
    <script>
        (function() {{
            const container = document.getElementById('splat-container');
            const scene = new THREE.Scene();
            scene.background = new THREE.Color(0x0d0d11);

            const camera = new THREE.PerspectiveCamera(55, container.clientWidth / container.clientHeight, 0.1, 100);

            const renderer = new THREE.WebGLRenderer({{ antialias: true }});
            renderer.setSize(container.clientWidth, container.clientHeight);
            renderer.setPixelRatio(window.devicePixelRatio);
            container.appendChild(renderer.domElement);

            const controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.05;

            const positions = new Float32Array({json.dumps(positions)});
            const colors = new Float32Array({json.dumps(colors)});

            const geometry = new THREE.BufferGeometry();
            geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
            geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

            const material = new THREE.PointsMaterial({{
                size: 0.06,
                vertexColors: true,
                sizeAttenuation: true
            }});

            const pointCloud = new THREE.Points(geometry, material);
            scene.add(pointCloud);

            geometry.computeBoundingBox();
            const center = new THREE.Vector3();
            geometry.boundingBox.getCenter(center);

            controls.target.copy(center);
            camera.position.set(center.x, center.y + 2.5, center.z - 4.5);
            controls.update();

            function animate() {{
                requestAnimationFrame(animate);
                controls.update();
                renderer.render(scene, camera);
            }}
            animate();
        }})();
    </script>
    """
    display(HTML(html_code))

# Execute Viewer (Try sensitivity="high" if the pothole is extremely shallow)
render_adaptive_pothole_3d("/content/0006.mp4", frame_idx=0, downsample=2, sensitivity="high")