import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")
PMC_EMAIL = os.getenv("PMC_EMAIL")

def send_pothole_email(lat, lon, image_url, severity):
    msg = EmailMessage()
    msg["From"] = SMTP_USER
    msg["To"] = PMC_EMAIL
    msg["Subject"] = "🚨 Urgent: Dangerous Pothole Detected in Pune"

    msg.set_content(f"""
Respected Sir/Madam,

A dangerous pothole has been detected on a public road.

📍 Location:
https://maps.google.com/?q={lat},{lon}

⚠ Severity: {severity}

🖼 Image Evidence:
{image_url}

This report was automatically generated by Road Sense Pro.

Regards,
Road Sense Pro (Automated System)
""")

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)

    print("✅ EMAIL SENT")
