-- =================================================================
-- 1. EXTENSIONS
-- Required for GPS distance math and AI visual fingerprint storage
-- =================================================================
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS vector;

-- =================================================================
-- 2. TABLES
-- =================================================================

-- A. Table for confirmed Potholes (The ones shown as Red Markers)
CREATE TABLE IF NOT EXISTS detections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_seen timestamp with time zone DEFAULT timezone('utc'::text, now()),
  
  -- Geographic Data
  latitude float8 NOT NULL,
  longitude float8 NOT NULL,
  heading float8 DEFAULT 0.0, -- Vehicle bearing (direction)
  geom geography(POINT, 4326), -- PostGIS point for fast radial search
  
  -- AI Metadata
  image_url text NOT NULL,
  severity text DEFAULT 'Moderate', -- Minor, Moderate, Severe
  embedding vector(2048), -- ResNet50 visual fingerprint
  report_count int DEFAULT 1, -- How many users reported this same hole
  
  -- User Identification
  user_id uuid REFERENCES auth.users(id), -- Linked to Supabase Auth
  user_email text,
  pc_node_id text -- ID of the PC that processed the image
);

-- B. Table for Road Telemetry (Heatmap / Breadcrumb trail)
CREATE TABLE IF NOT EXISTS road_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  latitude float8 NOT NULL,
  longitude float8 NOT NULL,
  roughness float8 NOT NULL, -- Standard Deviation of Z-axis acceleration
  
  session_id text,
  user_id uuid REFERENCES auth.users(id),
  user_email text
);

-- =================================================================
-- 3. INDEXING FOR PERFORMANCE
-- =================================================================
-- Spatial index for 8-meter radial searches
CREATE INDEX IF NOT EXISTS detections_geo_idx ON detections USING GIST(geom);
-- Index for User-specific filtering ("My Reports" toggle)
CREATE INDEX IF NOT EXISTS detections_user_id_idx ON detections(user_id);

-- =================================================================
-- 4. AUTOMATION: SYNC GEOM WITH LAT/LON
-- This trigger ensures that whenever a Lat/Lon is inserted, the 
-- PostGIS 'geom' column is automatically updated for math.
-- =================================================================
CREATE OR REPLACE FUNCTION update_geom() RETURNS trigger AS $$
BEGIN
  new.geom := ST_SetSRID(ST_MakePoint(new.longitude, new.latitude), 4326);
  RETURN new;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_geom_trigger
BEFORE INSERT OR UPDATE ON detections
FOR EACH ROW EXECUTE FUNCTION update_geom();

-- =================================================================
-- 5. FUNCTION: SPATIAL DEDUPLICATION SEARCH
-- Used by server.py to find existing potholes within 8 meters.
-- =================================================================
CREATE OR REPLACE FUNCTION find_candidates(search_lat float8, search_lon float8, radius_m float8)
RETURNS TABLE (
  id bigint,
  heading float8,
  report_count int,
  embedding vector(2048)
)
LANGUAGE sql
AS $$
  SELECT id, heading, report_count, embedding
  FROM detections
  WHERE ST_DWithin(
    geom, 
    ST_SetSRID(ST_MakePoint(search_lon, search_lat), 4326)::geography, 
    radius_m
  )
  AND last_seen > (now() - interval '90 days'); -- Ignore holes filled/fixed over 3 months ago
$$;

-- =================================================================
-- 6. SECURITY POLICIES (Row Level Security)
-- =================================================================
ALTER TABLE detections ENABLE ROW LEVEL SECURITY;
ALTER TABLE road_logs ENABLE ROW LEVEL SECURITY;

-- Detections Table Policies
CREATE POLICY "Enable read access for all users" ON detections 
FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON detections 
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can delete their own detections" ON detections 
FOR DELETE USING (auth.uid() = user_id);

-- Road Logs Table Policies
CREATE POLICY "Enable read for all" ON road_logs 
FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON road_logs 
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- =================================================================
-- 7. STORAGE PERMISSIONS
-- Allows users to view and the server to upload images.
-- =================================================================
-- Note: Ensure you have created a bucket named 'pothole-images' in the UI first.

-- Allow public to view images
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'pothole-images' );

-- Allow the Python Server (using Service Role) or Auth users to upload
CREATE POLICY "Authenticated Upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'pothole-images' );

-- Allow users to delete their own images from storage
CREATE POLICY "Owner Delete" 
ON storage.objects FOR DELETE 
USING ( bucket_id = 'pothole-images' AND (select auth.uid())::text = owner );
